version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha
    ports:
      - "5432:5432"
    container_name: python_db
    # networks:
    #   - application-network

  # nginx:
  #   image: nginx
  #   container_name: python_lb
  #   depends_on:
  #     - app
  #   networks:
  #     - application-network

  # app: 
  #   image: python:3.9
  #   depends_on:
  #     - db
  #   dockerfile: ./Dockerfile.dev
  #   container_name: pyhton_app
  #   command: python3 app/__init__.py
  #   networks:
  #     - application-network

# networks:
#   default:
#     external: true
#     name: application-network